// File generated by FlutterFire CLI / DACZDev Tech Lead
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1F4Dpk8dvm9aIWLnGMhYJjQiy_c5KTBo',
    appId: '1:608239754637:web:e656626d6ec95f14c771c4',
    messagingSenderId: '608239754637',
    projectId: 'olshopunugiri',
    authDomain: 'olshopunugiri.firebaseapp.com',
    databaseURL: 'https://olshopunugiri-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'olshopunugiri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1F4Dpk8dvm9aIWLnGMhYJjQiy_c5KTBo',
    appId: '1:608239754637:android:e656626d6ec95f14c771c4',
    messagingSenderId: '608239754637',
    projectId: 'olshopunugiri',
    databaseURL: 'https://olshopunugiri-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'olshopunugiri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1F4Dpk8dvm9aIWLnGMhYJjQiy_c5KTBo',
    appId: '1:608239754637:ios:e656626d6ec95f14c771c4',
    messagingSenderId: '608239754637',
    projectId: 'olshopunugiri',
    databaseURL: 'https://olshopunugiri-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'olshopunugiri.firebasestorage.app',
  );
}
